#!/bin/bash
# Test commands for Identity Chaincode
# Run these commands from the test-network directory in WSL

# Set environment variables for Org1
export PATH=${PWD}/../bin:$PATH
export FABRIC_CFG_PATH=$PWD/../config/
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
export CORE_PEER_MSPCONFIGPATH=${PWD}/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
export CORE_PEER_ADDRESS=localhost:7051

# Test 1: Issue a Credential
echo "=== Test 1: Issue Credential ==="
peer chaincode invoke -o localhost:7050 \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem \
  -C mychannel -n identity \
  --peerAddresses localhost:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt \
  --peerAddresses localhost:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt \
  -c '{"function":"IssueCredential","Args":["user1","0x1234567890abcdef","IssuerOrg","2024-01-01T00:00:00Z"]}'

sleep 10

# Test 2: Get the Credential
echo -e "\n=== Test 2: Get Credential ==="
peer chaincode query -C mychannel -n identity -c '{"function":"GetCredential","Args":["user1"]}'

# Test 3: Revoke the Credential
echo -e "\n=== Test 3: Revoke Credential ==="
peer chaincode invoke -o localhost:7050 \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem \
  -C mychannel -n identity \
  --peerAddresses localhost:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt \
  --peerAddresses localhost:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt \
  -c '{"function":"RevokeCredential","Args":["user1","Security breach"]}'

sleep 2

# Test 4: Query All Verifications
echo -e "\n=== Test 4: Query All Verifications ==="
peer chaincode query -C mychannel -n identity -c '{"function":"QueryVerifications","Args":[]}'

# Test 5: Verify Age (requires real Groth16 proof/public signals)
# Replace the proof/public signals JSON below with values generated by your zk-SNARK circuit.
: <<'AGE_PROOF_EXAMPLE'
echo -e "\n=== Test 5: Verify Age (Example) ==="

 peer chaincode invoke -o localhost:7050   --ordererTLSHostnameOverride orderer.example.com   --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem   -C mychannel -n identity   --peerAddresses localhost:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt   --peerAddresses localhost:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt   -c '{
    "function": "VerifyAge",
    "Args": [
      "user1",
      "21",
      "{\"pi_a\":[\"18910537133856858800994938786698580234575403637938318377158658218641064802755\",\"97928669636725502068643995011171938814461718871117124883459436224144687442\",\"1\"],\"pi_b\":[[\"18982720172429571324419063036134280191767553320227192818250986896779322441800\",\"21386849079462113483813620385700721227715776978494072950421238508489762542127\"],[\"19373143230646062872439441858110833167589785547047782716596844585578385795078\",\"17289097837163872855916758836723372515771495377015009813777667915258716125975\"],[\"1\",\"0\"]],\"pi_c\":[\"6247502684036547106671288451506680507453269271805914109156919387397639222688\",\"21521877375455335487035482171609221270902085309351286874187538521998231279710\",\"1\"],\"protocol\":\"groth16\",\"curve\":\"bn128\"}",
      "[\"1\"]"
    ]
  }'
AGE_PROOF_EXAMPLE

echo -e "\n=== Tests Complete ==="

