#!/bin/bash
# Test commands for Identity Chaincode
# Run these commands from the test-network directory in WSL

# Set environment variables for Org1
export PATH=${PWD}/../bin:$PATH
export FABRIC_CFG_PATH=$PWD/../config/
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
export CORE_PEER_MSPCONFIGPATH=${PWD}/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
export CORE_PEER_ADDRESS=localhost:7051

# Test 1: Issue a Credential
echo "=== Test 1: Issue Credential ==="
peer chaincode invoke -o localhost:7050 \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem \
  -C mychannel -n identity \
  --peerAddresses localhost:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt \
  --peerAddresses localhost:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt \
  -c '{"function":"IssueCredential","Args":["user1","0x1234567890abcdef","IssuerOrg","2024-01-01T00:00:00Z"]}'

sleep 2

# Test 2: Get the Credential
echo -e "\n=== Test 2: Get Credential ==="
peer chaincode query -C mychannel -n identity -c '{"function":"GetCredential","Args":["user1"]}'

# Test 3: Revoke the Credential
echo -e "\n=== Test 3: Revoke Credential ==="
peer chaincode invoke -o localhost:7050 \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem \
  -C mychannel -n identity \
  --peerAddresses localhost:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt \
  --peerAddresses localhost:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt \
  -c '{"function":"RevokeCredential","Args":["user1","Security breach"]}'

sleep 2

# Test 4: Query All Verifications
echo -e "\n=== Test 4: Query All Verifications ==="
peer chaincode query -C mychannel -n identity -c '{"function":"QueryVerifications","Args":[]}'

# Test 5: Verify Age (requires real Groth16 proof/public signals)
# Replace the proof/public signals JSON below with values generated by your zk-SNARK circuit.
: <<'AGE_PROOF_EXAMPLE'
echo -e "\n=== Test 5: Verify Age (Example) ==="
peer chaincode invoke -o localhost:7050 \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem \
  -C mychannel -n identity \
  --peerAddresses localhost:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt \
  --peerAddresses localhost:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt \
  -c '{"function":"VerifyAge","Args":["user1","21","{\"pi_a\":[...],\"pi_b\":[...],\"pi_c\":[...]}","[\"21\",\"0xCredentialHash\",\"1\"]"]}'
AGE_PROOF_EXAMPLE

echo -e "\n=== Tests Complete ==="

