#!/bin/bash
# End-to-end test script for Merkle tree integration

cd "$(dirname "$0")/test-network"

# Set environment variables for Org1
export PATH=${PWD}/../bin:$PATH
export FABRIC_CFG_PATH=$PWD/../config/
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
export CORE_PEER_MSPCONFIGPATH=${PWD}/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
export CORE_PEER_ADDRESS=localhost:7051

ROOT_HASH="8412550286024366496761021225573402804105404741730529033897646272334110688748"

echo "=== Step 1: Issue Credential with Merkle Root ==="
peer chaincode invoke -o localhost:7050 \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem \
  -C mychannel -n identity \
  --peerAddresses localhost:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt \
  --peerAddresses localhost:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt \
  -c "{\"function\":\"IssueCredential\",\"Args\":[\"user123\",\"$ROOT_HASH\",\"TrustedIssuer\",\"2024-11-24T00:00:00Z\"]}"

sleep 5

echo -e "\n=== Step 2: Get Credential to Verify ==="
peer chaincode query -C mychannel -n identity -c '{"function":"GetCredential","Args":["user123"]}'

echo -e "\n=== Step 3: Test VerifyAge with Merkle Root Binding ==="
# Using a simple test proof (this would be generated by your circuit in production)
PROOF='{"pi_a":["1","1","1"],"pi_b":[["1","1"],["1","1"],["1","0"]],"pi_c":["1","1","1"],"protocol":"groth16","curve":"bn128"}'
PUBLIC='["1"]'

echo "Calling VerifyAge with:"
echo "  - userID: user123"
echo "  - minimumAge: 18"
echo "  - rootHash: $ROOT_HASH"

peer chaincode invoke -o localhost:7050 \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem \
  -C mychannel -n identity \
  --peerAddresses localhost:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt \
  --peerAddresses localhost:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt \
  -c "{\"function\":\"VerifyAge\",\"Args\":[\"user123\",\"18\",\"$PROOF\",\"$PUBLIC\",\"$ROOT_HASH\"]}"

echo -e "\n=== Step 4: Test with WRONG root hash (should fail) ==="
WRONG_HASH="9999999999999999999999999999999999999999999999999999999999999999999999999999"

peer chaincode invoke -o localhost:7050 \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem \
  -C mychannel -n identity \
  --peerAddresses localhost:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt \
  --peerAddresses localhost:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt \
  -c "{\"function\":\"VerifyAge\",\"Args\":[\"user123\",\"18\",\"$PROOF\",\"$PUBLIC\",\"$WRONG_HASH\"]}" || echo "EXPECTED: Failed due to rootHash mismatch"

echo -e "\n=== Test Complete ==="
